name: GANterfactual
channels:
  - conda-forge
  - apple
  - defaults
dependencies:
  - apple::tensorflow-deps=2.6.0
  - tensorflow-addons
  - matplotlib
  - pip
  - scikit-learn
  - scikit-image
  - albumentations
  - pip:
    - tensorflow-macos==2.6.0
    - tensorflow-metal
    - tensorflow-datasets==4.4.0
    - tensorflow-addons